// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FileStorageInterface is an autogenerated mock type for the FileStorageInterface type
type FileStorageInterface struct {
	mock.Mock
}

// Upload provides a mock function with given fields: ctx, path, data
func (_m *FileStorageInterface) Upload(ctx context.Context, path string, data []byte) error {
	ret := _m.Called(ctx, path, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, path, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
